version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "5432:5432"
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
      - ./data/acme.json:/etc/traefik/acme.json
    networks:
      - paas-net

  postgres-a:
    image: postgres:15
    container_name: postgres-a
    environment:
      POSTGRES_USER: user_a
      POSTGRES_PASSWORD: password_a
      POSTGRES_DB: db_a
    ports:
      - "4500:5432"
    volumes:
      - ./data/postgres-a:/var/lib/postgresql/data
    command: -p 4500
    networks:
      - paas-net

  postgres-b:
    image: postgres:15
    container_name: postgres-b
    environment:
      POSTGRES_USER: user_b
      POSTGRES_PASSWORD: password_b
      POSTGRES_DB: db_b
    ports:
      - "5500:5432"
    volumes:
      - ./data/postgres-b:/var/lib/postgresql/data
    command: -p 5500
    networks:
      - paas-net

networks:
  paas-net:
    driver: bridge