global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  postgres:
    address: ":5432"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    exposedByDefault: false

log:
  level: INFO