global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  postgres:
    address: ":5432"
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "hello@brimble.app"
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web