tcp:
  routers:
    router-x:
      entryPoints:
        - postgres
      rule: "HostSNI(`x.brimble.app`)"
      service: postgres-a
      tls:
        passthrough: false
        certresolver: letsencrypt
    router-y:
      entryPoints:
        - postgres
      rule: "HostSNI(`y.brimble.app`)"
      service: postgres-b
      tls:
        passthrough: false
        certresolver: letsencrypt

  services:
    postgres-a:
      loadBalancer:
        servers:
          - address: "postgres-a:4500"
    postgres-b:
      loadBalancer:
        servers:
          - address: "postgres-b:5500"